### ISSUE TITLE
Aprimorar eval para calcular grupos isolados

### ISSUE THREAD

**Issue by fmaachadoo** [fmaachadoo/Latym-language#16]
# Aprimorar eval
Implementar o uso de ```posthac die``` e ```usque huc```

#### Condição de fechamento desta issue: 
Fazer com que o eval consiga processar calculos como:
input : ```posthac die 3 adde 2 usque huc minuas 2 adde posthac die 5 usque huc```
output: ```8```

**Comment by freitasc** [comment]
Matemática com múltiplos parenteses e grupos isolados são permitidos nesse momento.
